- hosts: 
  - example_routers
 
  vars:
    example_var: "test"
  tasks:
    - name: sysctl base configurations
      import_role:
        name: lanefu.clammy.sysctl_base
      tags:
        - core
        - sysctl
        - system
    - name: configure wan interface with netplan 
      import_role:
        name: lanefu.clammy.netplan
      vars:
        netplan_configuration: "{{ wan_netplan_configuration }}"
        netplan_config_file: "{{ wan_netplan_config_file }}"
        netplan_apply: True
      tags:
        - netplan
        - wan
        - interfaces
##FIXME need more elegant way in role to apply / flush
    - name: Flush handlers to apply netplan WAN now
      meta: flush_handlers
      tags:
        - netplan
        - wan
        - interfaces
    - name: configure lan interfaces with netplan 
      import_role:
        name: lanefu.clammy.netplan
      vars:
        netplan_configuration: "{{ lan_netplan_configuration }}"
        netplan_config_file: "{{ lan_netplan_config_file }}"
        netplan_apply: True
        netplan_remove_existing: false
      tags:
        - netplan
        - lan
        - interfaces
##FIXME need more elegant way in role to apply / flush
    - name: Flush handlers to apply netplan LAN now
      meta: flush_handlers
      tags:
        - netplan
        - lan
        - interfaces
    - name: Wireguard interfaces
      debug:
        msg: you would probably do wireguard interfaces here
    - name: dnsmasq role
      import_role:
        name: mrlesmithjr.ansible_dnsmasq
      tags:
        - dns
        - dhcp
        - dnsmasq
    - name: frr routing role
      import_role:
        name: lanefu.clammy.frr
      tags:
        - frr
        - routing
    - name: foomuuri firewall role
      import_role:
        name: lanefu.clammy.foomuuri
      tags:
        - foomuuri
        - firewall
    - name: Install extra router creature comforts
      import_role:
        name: lanefu.clammy.creature_comforts
      tags:
        - extras
        - comforts
    - name: reminders
      debug:
        msg: dont forget to finish the project
    - name: reminders
      debug:
        msg: dont forget to finish the project
    - name: reminders
      debug:
        msg: dont forget to finish the project
