---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: containers.podman
  - name: community.general
roles:
  - name: geerlingguy.ntp
  - name: frzk.chrony
    src: https://github.com/Frzk/ansible-role-chrony.git
    version: main
